//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warzywniak
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProduct
    {
        public OrderProduct()
        {
        }
        public OrderProduct(OrderProduct op, decimal sum)
        {
            this.OrderId = op.OrderId;
            this.OrderProductId = op.OrderProductId;
            this.ProductId = op.ProductId;
            this.Quantity = op.Quantity;
            this.Product = op.Product;
            this.Order = op.Order;
            this.Sum = op.Quantity * op.Product.ProductPrice;
        }
        public int OrderProductId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public decimal Quantity { get; set; }
        public decimal Sum { get; set; }

        public byte[] RowVersion { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
